name: Publish to npm on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish:
    name: Test, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Verify release tag matches package version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Tag: ${TAG_VERSION} | package.json: ${PKG_VERSION}"
          if [ "${TAG_VERSION}" != "v${PKG_VERSION}" ] && [ "${TAG_VERSION}" != "${PKG_VERSION}" ]; then
            echo "Release tag must match package.json version (v${PKG_VERSION} or ${PKG_VERSION})." >&2
            exit 1
          fi

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build:simple --silent

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Enable provenance for npm publish (requires id-token permission)
          npm publish --provenance --access public
